// Code generated by ent, DO NOT EDIT.

package http

import (
	"ent-sample/ent"
	"ent-sample/ent/todo"
	"ent-sample/ent/user"
	"net/http"
	"strings"

	"github.com/mailru/easyjson"
	"go.uber.org/zap"
)

// Create creates a new ent.Todo and stores it in the database.
func (h TodoHandler) Create(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	var d TodoCreateRequest
	if err := easyjson.UnmarshalFromReader(r.Body, &d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		BadRequest(w, "invalid json string")
		return
	}
	// Validate the data.
	errs := make(map[string]string)
	if d.Text == nil {
		errs["text"] = `missing required field: "text"`
	} else if err := todo.TextValidator(*d.Text); err != nil {
		errs["text"] = strings.TrimPrefix(err.Error(), "todo: ")
	}
	if d.Status != nil {
		if err := todo.StatusValidator(*d.Status); err != nil {
			errs["status"] = strings.TrimPrefix(err.Error(), "todo: ")
		}
	}
	if len(errs) > 0 {
		l.Info("validation failed", zapFields(errs)...)
		BadRequest(w, errs)
		return
	}
	// Save the data.
	b := h.client.Todo.Create()
	if d.Text != nil {
		b.SetText(*d.Text)
	}
	if d.CreatedAt != nil {
		b.SetCreatedAt(*d.CreatedAt)
	}
	if d.Status != nil {
		b.SetStatus(*d.Status)
	}
	if d.Priority != nil {
		b.SetPriority(*d.Priority)
	}
	if d.Children != nil {
		b.AddChildIDs(d.Children...)
	}
	if d.Parent != nil {
		b.SetParentID(*d.Parent)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create todo", zap.Error(err))
			InternalServerError(w, nil)
		}
		return
	}
	// Store id of fresh entity to log errors for the reload.
	id := e.ID
	// Reload entry.
	q := h.client.Todo.Query().Where(todo.ID(e.ID))
	ret, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			BadRequest(w, msg)
		default:
			l.Error("could not read todo", zap.Error(err), zap.Int("id", id))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("todo rendered", zap.Int("id", id))
	easyjson.MarshalToHTTPResponseWriter(NewTodo1977301413View(ret), w)
}

// Create creates a new ent.User and stores it in the database.
func (h UserHandler) Create(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	var d UserCreateRequest
	if err := easyjson.UnmarshalFromReader(r.Body, &d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		BadRequest(w, "invalid json string")
		return
	}
	// Validate the data.
	errs := make(map[string]string)
	if d.Name == nil {
		errs["name"] = `missing required field: "name"`
	} else if err := user.NameValidator(*d.Name); err != nil {
		errs["name"] = strings.TrimPrefix(err.Error(), "user: ")
	}
	if d.Email == nil {
		errs["email"] = `missing required field: "email"`
	} else if err := user.EmailValidator(*d.Email); err != nil {
		errs["email"] = strings.TrimPrefix(err.Error(), "user: ")
	}
	if d.Password == nil {
		errs["password"] = `missing required field: "password"`
	} else if err := user.PasswordValidator(*d.Password); err != nil {
		errs["password"] = strings.TrimPrefix(err.Error(), "user: ")
	}
	if d.Status != nil {
		if err := user.StatusValidator(*d.Status); err != nil {
			errs["status"] = strings.TrimPrefix(err.Error(), "user: ")
		}
	}
	if len(errs) > 0 {
		l.Info("validation failed", zapFields(errs)...)
		BadRequest(w, errs)
		return
	}
	// Save the data.
	b := h.client.User.Create()
	if d.Name != nil {
		b.SetName(*d.Name)
	}
	if d.Email != nil {
		b.SetEmail(*d.Email)
	}
	if d.Password != nil {
		b.SetPassword(*d.Password)
	}
	if d.CreatedAt != nil {
		b.SetCreatedAt(*d.CreatedAt)
	}
	if d.Status != nil {
		b.SetStatus(*d.Status)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create user", zap.Error(err))
			InternalServerError(w, nil)
		}
		return
	}
	// Store id of fresh entity to log errors for the reload.
	id := e.ID
	// Reload entry.
	q := h.client.User.Query().Where(user.ID(e.ID))
	ret, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			BadRequest(w, msg)
		default:
			l.Error("could not read user", zap.Error(err), zap.Int("id", id))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("user rendered", zap.Int("id", id))
	easyjson.MarshalToHTTPResponseWriter(NewUser2774811467View(ret), w)
}
