// Code generated by ent, DO NOT EDIT.

package http

import (
	"ent-sample/ent"
	"ent-sample/ent/todo"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/mailru/easyjson"
	"go.uber.org/zap"
)

// Children fetches the ent.children attached to the ent.Todo
// identified by a given url-parameter from the database and renders it to the client.
func (h TodoHandler) Children(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Children"))
	// ID is URL parameter.
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", chi.URLParam(r, "id")), zap.Error(err))
		BadRequest(w, "id must be an integer")
		return
	}
	// Create the query to fetch the children attached to this todo
	q := h.client.Todo.Query().Where(todo.ID(id)).QueryChildren()
	page := 1
	if d := r.URL.Query().Get("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			l.Info("error parsing query parameter 'page'", zap.String("page", d), zap.Error(err))
			BadRequest(w, "page must be an integer greater zero")
			return
		}
	}
	itemsPerPage := 30
	if d := r.URL.Query().Get("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			l.Info("error parsing query parameter 'itemsPerPage'", zap.String("itemsPerPage", d), zap.Error(err))
			BadRequest(w, "itemsPerPage must be an integer greater zero")
			return
		}
	}
	es, err := q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage).All(r.Context())
	if err != nil {
		l.Error("error fetching todos from db", zap.Error(err))
		InternalServerError(w, nil)
		return
	}
	l.Info("todos rendered", zap.Int("amount", len(es)))
	easyjson.MarshalToHTTPResponseWriter(NewTodo1977301413Views(es), w)
}

// Parent fetches the ent.parent attached to the ent.Todo
// identified by a given url-parameter from the database and renders it to the client.
func (h TodoHandler) Parent(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Parent"))
	// ID is URL parameter.
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", chi.URLParam(r, "id")), zap.Error(err))
		BadRequest(w, "id must be an integer")
		return
	}
	// Create the query to fetch the parent attached to this todo
	q := h.client.Todo.Query().Where(todo.ID(id)).QueryParent()
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			BadRequest(w, msg)
		default:
			l.Error("could-not-read-todo", zap.Error(err), zap.Int("id", id))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("todo rendered", zap.Int("id", e.ID))
	easyjson.MarshalToHTTPResponseWriter(NewTodo1977301413View(e), w)
}
