// Code generated by ent, DO NOT EDIT.

package http

import (
	"ent-sample/ent/todo"
	"ent-sample/ent/user"
	"time"
)

// Payload of a ent.Todo create request.
type TodoCreateRequest struct {
	Text      *string      `json:"text"`
	CreatedAt *time.Time   `json:"created_at"`
	Status    *todo.Status `json:"status"`
	Priority  *int         `json:"priority"`
	Children  []int        `json:"children"`
	Parent    *int         `json:"parent"`
}

// Payload of a ent.Todo update request.
type TodoUpdateRequest struct {
	Text     *string      `json:"text"`
	Status   *todo.Status `json:"status"`
	Priority *int         `json:"priority"`
	Children []int        `json:"children"`
	Parent   *int         `json:"parent"`
}

// Payload of a ent.User create request.
type UserCreateRequest struct {
	Name      *string      `json:"name"`
	Email     *string      `json:"email"`
	Password  *string      `json:"password"`
	CreatedAt *time.Time   `json:"created_at"`
	Status    *user.Status `json:"status"`
}

// Payload of a ent.User update request.
type UserUpdateRequest struct {
	Name     *string      `json:"name"`
	Email    *string      `json:"email"`
	Password *string      `json:"password"`
	Status   *user.Status `json:"status"`
}
